services: # local 작업 용 compose.yml (스프링에서 사용할 디비)
  db-server:
    container_name: localDB
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gs4cutdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
