services:

  mysql-prod:
    container_name: mysql-prod
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: gs4cutdb
      MYSQL_USER: admin
      TZ: Asia/Seoul
    volumes:
      - mysql-prod-data:/var/lib/mysql
    networks:
      - prod-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis-prod:
    container_name: redis-prod
    image: redis
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-prod-data:/data
    networks:
      - prod-net
    command: redis-server --appendonly yes

  minio-prod:
    container_name: minio-prod
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - minio-prod-data:/data
    networks:
      - prod-net
    command: server /data

  was-prod-blue:
    container_name: was-prod-blue
    # 젠킨스가 넘겨준 이미지 이름과 빌드 번호를 사용
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    environment:
      - PROFILE=prod
    depends_on:
      - mysql-prod
      - redis-prod
    networks:
      - prod-net

  was-prod-green:
    container_name: was-prod-green
    # 젠킨스가 넘겨준 이미지 이름과 빌드 번호를 사용
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    environment:
      - PROFILE=prod
    depends_on:
      - mysql-prod
      - redis-prod
    networks:
      - prod-net

networks:
  prod-net:
    external: true

volumes:
  mysql-prod-data:
  redis-prod-data:
  minio-prod-data: