services:

  mysql-test:
    container_name: mysql-test
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: gs4cutdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-test-data:/var/lib/mysql
    networks:
      - test-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env

  redis-test:
    container_name: redis-test
    image: redis
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-test-data:/data
    networks:
      - test-net
    command: redis-server --appendonly yes

  minio-test:
    container_name: minio-test
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - minio-test-data:/data
    networks:
      - test-net
    command: server /data
    env_file:
      - .env

  was-test-blue:
    container_name: was-test-blue
    # 젠킨스가 넘겨준 이미지 이름과 빌드 번호를 사용
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    environment:
      - PROFILE=dev
    depends_on:
      - mysql-test
      - redis-test
    networks:
      - test-net
    env_file:
      - .env

  was-test-green:
    container_name: was-test-green
    # 젠킨스가 넘겨준 이미지 이름과 빌드 번호를 사용
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    environment:
      - PROFILE=dev
    depends_on:
      - mysql-test
      - redis-test
    networks:
      - test-net
    env_file:
      - .env

networks:
  test-net:
    external: true

volumes:
  mysql-test-data:
  redis-test-data:
  minio-test-data: