
# 1. HTTP (Port 80) -> HTTPS (Port 443) 리다이렉트
server {
    listen 80;
    server_name i14e208.p.ssafy.io;

    # Certbot 인증을 위한 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 나머지 모든 요청은 HTTPS로 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. HTTPS (Port 443) - 메인 서버 설정
server {
    listen 443 ssl;
    server_name i14e208.p.ssafy.io;

    # SSL 인증서 설정 (Certbot 경로)
    ssl_certificate /etc/letsencrypt/live/i14e208.p.ssafy.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/i14e208.p.ssafy.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # 변수 파일 포함 (Blue/Green 배포)
    include /etc/nginx/conf.d/prod-upstream.inc;      # 운영용 변수 ($prod_upstream)
    include /etc/nginx/conf.d/test-upstream.inc; # 테스트용 변수 ($test_upstream)

    # Docker 내부 DNS Resolver (변수로 proxy_pass 할때 필요한 설정)
    resolver 127.0.0.11 valid=5s;

    # 운영 API (Production) -> /api
    location /api/ {
        # 운영 서버로 트래픽 전달 (prod-blue or prod-green)
        proxy_pass $prod_upstream;

        # 실제 접속자 정보 전달
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    # 테스트 API (Dev/Test) -> /test-api
    location /test-api/ {

        # Rewrite (경로 변경 : 엔드포인트 지나면 원래 백엔드 코드 형식대로 요청 url 변경)
        # 외부 요청: /test-api/~  --->  내부 전달: /api/~
        rewrite ^/test-api/(.*)$ /api/$1 break;

        # 테스트 서버로 트래픽 전달 (test-blue or test-green)
        proxy_pass $test_upstream;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    # 프런트엔드 배포된 웹서버 -> 루트 경로
    location / {

        root /usr/share/nginx/dist; # 호스트로 부터 마운트 받음
        index index.html;
        try_files $uri $uri/ /index.html; # SPA 라우팅 문제 해결용
    }
}